### ISSUE TITLE
Cannot find class: UuidTypeHandler error

### ISSUE THREAD

**Issue by nedijahij** [harawata/mybatis-issues#26]
I have tried to import this tutorial to my Spring Boot project and I got error `java.lang.ClassNotFoundException: Cannot find class: UuidTypeHandler`

In my application.yml i have:
```
mybatis:
  type-handlers-package: com.test.typeHandler,typeHandler

# UuidTypeHandler.kt class is living at com.test.typeHandler.UuidTypeHandler
```

In my mapper i have:
```
@Insert("""
        <script>
            INSERT
                INTO People(id)
            VALUES
                <foreach collection="people" item="person" index="index" open="(" separator = "),(" close=")">
                    #{person.id, javaType=java.util.UUID, jdbcType=OTHER, typeHandler=UuidTypeHandler}
                </foreach>
        </script>
    """)
```

If i have  typeHandler=full.package.UuidTypeHandler, then it works pretty well but if i have to put a full path then why we need type-handlers-package inside application.yml? 
And in the example, I don't see you have to use `javaType=java.util.UUID, jdbcType=OTHER, typeHandler=UuidTypeHandler` too.
So, please help me fix this because I don't want to have a full path type all the time or if possible, without adding those extra javaType..typeHandler... thanks

**Comment by harawata** [comment]
Hi @nedijahij ,

`#{person.id}` should work just fine. Have you tried that?
If it didn't work, please share a small project on your GitHub repo and I'll look into it.

**Comment by nedijahij** [comment]
I have tried again on another computer and it is working now. Maybe because cache or something wrong with my Kotlin converted code. Thank for your assist anyway.
